### ISSUE TITLE
_linear do not exist

### ISSUE THREAD

**Issue by tiehan** [Szarad/PDFtoLATEX-conversion#2]
python train.py --help

Traceback (most recent call last):
  File "train.py", line 5, in <module>
    import random, time, os, model
  File "/Users/tanqianshan/Documents/project/PDFtoLATEX-conversion/model.py", line 35, in <module>
    linear = rnn_cell._linear  
AttributeError: 'module' object has no attribute '_linear'

**Comment by tiehan** [comment]
from tensorflow.contrib.rnn.python.ops import rnn_cell
linear = rnn_cell._Linear

for tensorflow v1.5
